In [1]:
import sqlite3

In [14]:
db_path = "..database/ev_charging.db"

In [3]:
conn = sqlite3.connect(db_path)

In [ ]:
import pandas as pd

processed_path = "../data/processed"

charging_df = pd.read_csv(
    processed_path + "/charging_sessions.csv"
)

station_df = pd.read_csv(
    processed_path + "/station_summary.csv"
)

In [6]:
charging_df.to_sql(
    "charging_sessions",
    conn,
    if_exists="replace",
    index=False
)

station_df.to_sql(
    "station_summary",
    conn,
    if_exists="replace",
    index=False
)

52

In [7]:
pd.read_sql(
    "SELECT COUNT(*) AS total_sessions FROM charging_sessions",
    conn
)

   total_sessions
0            2499

In [8]:
pd.read_sql(
    "SELECT COUNT(*) AS total_stations FROM station_summary",
    conn
)

   total_stations
0              52

In [10]:
#Top 5 stations by number of sessions

query = """
SELECT
    stationID,
    session_count,
    total_kWh
FROM station_summary
ORDER BY session_count DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

     stationID  session_count  total_kWh
0  2-39-139-28            107   1031.297
1  2-39-138-29             90    663.840
2  2-39-129-17             85    688.990
3  2-39-127-19             85    656.010
4  2-39-131-30             79    730.073

In [ ]:
#Which hours have the highest charging demand?

query = """
SELECT
    hour,
    COUNT(*) AS session_count,
    SUM(kWhDelivered) AS total_kWh
FROM charging_sessions
GROUP BY hour
ORDER BY session_count DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

   hour  session_count    total_kWh
0    15            519  4338.023818
1    16            331  2960.704000
2    14            174  1649.155835
3    17            173  1689.888000
4     1            151  1343.862000

In [13]:
#top stations by total energy delivered.

query = """
SELECT
    stationID,
    session_count,
    total_kWh,
    avg_kWh_per_session
FROM station_summary
ORDER BY total_kWh DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

     stationID  session_count    total_kWh  avg_kWh_per_session
0  2-39-139-28            107  1031.297000             9.638290
1  2-39-91-437             64   883.128366            13.798881
2   2-39-95-27             59   739.984000            12.542102
3  2-39-131-30             79   730.073000             9.241430
4  2-39-79-379             72   714.377000             9.921903